---
- name: Ensure build directory exists
  file: 
    path: "qemu/build" 
    state: directory

- name: download QEMU source 
  get_url:
    validate_certs: false
    url: "{{ qemu.dl_url }}"
    dest: "qemu/src.tar.xz"

# TODO: unarchive did not work with my version of ansible 
# https://github.com/ansible/ansible-modules-core/issues/3241
# waiting for uncompress module
- name: Unarchive a file
  command: "tar -x -v -C qemu -J -f qemu/src.tar.xz"
  args:
    creates: "qemu/{{ qemu.src_name }}"

- name: Configure
  command: "../{{ qemu.src_name }}/configure --target-list=aarch64-linux-user --static"
  args:
    chdir: "qemu/build"
    creates: "config.status"

- name: Make
  command: "make -j8"
  args:
    chdir: "qemu/build"
    creates: "aarch64-linux-user/qemu-aarch64"

#     && make install

- name: Cleanup the build folder
  file: 
    path: "qemu" 
    state: absent
